Repository AtB-AS/planner-web, pull requests merged in 2023-12, with the labels that each got.

#111 fix: revalidation on connect for autocomplete
  src/page-modules/departures/client/geocoder/index.ts
Labels: C-bug

#117 feat: show dotted line for foot legs
  src/components/map/use-map-legs.ts
  src/pages/assistant/index.tsx
Labels: C-feature

#108 feat: adds geolocation to widget
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-feature

#118 fix: Handle no search result for widget
  src/page-modules/departures/server/geocoder/encoders.ts
  src/widget/widget.ts
Labels: C-bug

#109 feat: show all transport modes for a stop place
  src/components/line-chip/index.tsx
  src/components/line-chip/line-chip.module.css
  src/components/search/search.tsx
  src/components/venue-icon/index.tsx
  src/page-modules/assistant/details/trip-section/interchange-section.tsx
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/departures/nearest-stop-places/index.tsx
  src/page-modules/departures/server/journey-planner/index.ts
  src/page-modules/departures/server/journey-planner/journey-gql/nearest-stop-places.gql
  src/page-modules/departures/server/journey-planner/validators.ts
Labels: C-feature

#127 feat: show details for a non-transit trip
  src/page-modules/assistant/__tests__/assistant-data.fixture.ts
  src/page-modules/assistant/non-transit-pill/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
Labels: C-feature

#126 feat: adds cache-control strategy for widget
  next.config.js
Labels: C-feature

#130 chore: upgrades all dependencies
  .github/workflows/test.yml
  .github/workflows/tsc.yml
  package.json
  src/modules/transport-mode/filter/types.ts
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/widget/copy-markup.tsx
  yarn.lock
Labels: C-chore

#133 fix: avoid crashing details if browser not supports webgl
  src/components/map/map.module.css
  src/components/map/map.tsx
  src/tests/setup.ts
Labels: C-bug

#129 fix: show correct trip duration based on rounded times
  src/page-modules/assistant/details/details-header/index.tsx
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/utils/date.ts
Labels: C-bug

#128 fix: update meta description
  src/translations/common/layout.ts
Labels: C-bug

#119 feat: add placeholders to search
  .gitignore
  .vscode/settings.json
  src/components/search/__tests__/search.test.tsx
  src/components/search/search.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/departures/layout.tsx
  src/translations/pages/assistant.ts
  src/translations/pages/departures.ts
Labels: C-feature

#123 feat: component to toggle between the assistant and departures pages.
  src/components/tab-link/index.ts
  src/components/tab-link/tab-link.module.css
  src/components/tab-link/tab-link.tsx
  src/layouts/shared/page-header.tsx
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/layout.tsx
  src/translations/components/index.ts
  src/translations/components/tab-link.ts
Labels: C-feature

#138 breaking-change(widget): adds new version of widget (v1.0.0)
  README.md
  package.json
  public/widget/GYJwhgtkA/1.0.0/planner-web.css
  public/widget/GYJwhgtkA/1.0.0/planner-web.d.ts
  public/widget/GYJwhgtkA/1.0.0/planner-web.mjs
  public/widget/GYJwhgtkA/1.0.0/planner-web.umd.js
  public/widget/HYMw1kA/1.0.0/planner-web.css
  public/widget/HYMw1kA/1.0.0/planner-web.d.ts
  public/widget/HYMw1kA/1.0.0/planner-web.mjs
  public/widget/HYMw1kA/1.0.0/planner-web.umd.js
  public/widget/IYFwRkA/1.0.0/planner-web.css
  public/widget/IYFwRkA/1.0.0/planner-web.d.ts
  public/widget/IYFwRkA/1.0.0/planner-web.mjs
  public/widget/IYFwRkA/1.0.0/planner-web.umd.js
  scripts/generate-widget-stat.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/pages/widget/index.tsx
Labels: breaking

#141 breaking-change(widget): fixes issue with widget without same reset css and base styling
  package.json
  public/widget/GYJwhgtkA/2.0.0/planner-web.css
  public/widget/GYJwhgtkA/2.0.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.0.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.0.0/planner-web.umd.js
  public/widget/HYMw1kA/2.0.0/planner-web.css
  public/widget/HYMw1kA/2.0.0/planner-web.d.ts
  public/widget/HYMw1kA/2.0.0/planner-web.mjs
  public/widget/HYMw1kA/2.0.0/planner-web.umd.js
  public/widget/IYFwRkA/2.0.0/planner-web.css
  public/widget/IYFwRkA/2.0.0/planner-web.d.ts
  public/widget/IYFwRkA/2.0.0/planner-web.mjs
  public/widget/IYFwRkA/2.0.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/pages/widget/index.tsx
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-bug, breaking

#143 docs: fix styling for widget doc page
  src/page-modules/widget/copy-markup.tsx
  src/page-modules/widget/widget.module.css
  src/pages/widget/index.tsx
Labels: C-bug

#144 fix: remove unused hamburger menu
  src/layouts/base/index.tsx
  src/layouts/shared/page-header.module.css
  src/layouts/shared/page-header.tsx
Labels: bug, C-bug

#136 fix: show "Ferry from" if it's ferry and not boat
  src/modules/transport-mode/icon/index.tsx
  src/modules/transport-mode/index.ts
  src/modules/transport-mode/utils.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/translations/pages/assistant.ts
Labels: C-bug

#142 fix: Minor change to improve layout in mobile view.
  src/components/search/search.module.css
  src/page-modules/assistant/assistant.module.css
  src/page-modules/departures/departures.module.css
Labels: C-bug

#146 fix: use point in "From" as focus point
  src/page-modules/assistant/layout.tsx
Labels: C-bug

#149 feat: connect to firebase
  .env.example
  .github/workflows/docker.yml
  Dockerfile
  package.json
  src/modules/firebase/firebase.ts
  src/modules/firebase/index.ts
  src/modules/firebase/tariff-zones.ts
  src/modules/firebase/types.ts
  src/tests/setup.ts
  yarn.lock
Labels: C-feature

#152 fix: assistant page search title
  src/translations/pages/assistant.ts
Labels: C-bug

#151 feat: new focus point for FRAM
  .github/workflows/docker.yml
  src/page-modules/departures/server/geocoder/index.ts
Labels: C-feature

#148 feat: adds cookieless statistics for search
  .github/workflows/docker.yml
  Dockerfile
  src/components/search/search.tsx
  src/modules/firebase/analytics.ts
  src/modules/firebase/firebase.ts
  src/modules/firebase/index.ts
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/layout.tsx
  src/pages/_app.tsx
Labels: C-feature

#154 fix: quay sorting
  src/page-modules/departures/server/journey-planner/utils.ts
Labels: C-bug

#155 feat: adds english, nynorsk to widget
  package.json
  public/widget/GYJwhgtkA/2.1.0/planner-web.css
  public/widget/GYJwhgtkA/2.1.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.1.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.1.0/planner-web.umd.js
  public/widget/HYMw1kA/2.1.0/planner-web.css
  public/widget/HYMw1kA/2.1.0/planner-web.d.ts
  public/widget/HYMw1kA/2.1.0/planner-web.mjs
  public/widget/HYMw1kA/2.1.0/planner-web.umd.js
  public/widget/IYFwRkA/2.1.0/planner-web.css
  public/widget/IYFwRkA/2.1.0/planner-web.d.ts
  public/widget/IYFwRkA/2.1.0/planner-web.mjs
  public/widget/IYFwRkA/2.1.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/pages/widget/index.tsx
  src/widget/widget.ts
Labels: C-feature

#156 fix: removes wrong SoMe links
  orgs/fram.json
Labels: C-bug

#157 fix: keyboard navigation order with map
  src/components/map/map.tsx
  src/page-modules/departures/nearest-stop-places/index.tsx
  src/page-modules/departures/stop-place/index.tsx
Labels: C-bug

#153 feat: swap departBy and arriveBy in assistant
  src/modules/search-time/selector/__tests__/selector.test.tsx
  src/modules/search-time/types.ts
  src/translations/modules/search-time.ts
Labels: C-feature

#159 fix: add correct data to estimated calls for next departures
  src/page-modules/departures/client/journey-planner/index.ts
  src/page-modules/departures/server/journey-planner/index.ts
  src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
  src/page-modules/departures/stop-place/index.tsx
  src/pages/api/departures/journey-planner.ts
Labels: C-bug

#160 feat: error page
  src/page-modules/error/error-content.module.css
  src/page-modules/error/error-content.tsx
  src/page-modules/error/index.ts
  src/pages/_error.tsx
  src/translations/pages/error.ts
  src/translations/pages/index.ts
Labels: C-feature

#158 feat: make the view of cancelled departures appear more similar as in the app
  .gitignore
  package.json
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/stop-place/stop-place.module.css
  yarn.lock
Labels: C-chore

#165 fix: reload page manually to refresh estimated calls
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/stop-place/stop-place.module.css
Labels: C-bug

#164 fix: only show loading when both to and from are selected
  src/components/loading-empty-results/index.tsx
  src/page-modules/assistant/layout.tsx
Labels: C-bug

#166 feat: link to home page
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  src/layouts/shared/page-header.module.css
  src/modules/org-data/index.tsx
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/departures.module.css
  src/page-modules/departures/layout.tsx
  src/translations/pages/assistant.ts
  src/translations/pages/departures.ts
Labels: C-feature

#167 fix: add correct firebase app ID to FRAM prod
  .github/workflows/docker.yml
Labels: C-bug

#168 fix(widget): add base url to reverse and autocomplete fetch path
  public/widget/GYJwhgtkA/2.1.0/planner-web.css
  public/widget/GYJwhgtkA/2.1.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.1.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.1.0/planner-web.umd.js
  public/widget/HYMw1kA/2.1.0/planner-web.css
  public/widget/HYMw1kA/2.1.0/planner-web.d.ts
  public/widget/HYMw1kA/2.1.0/planner-web.mjs
  public/widget/HYMw1kA/2.1.0/planner-web.umd.js
  public/widget/IYFwRkA/2.1.0/planner-web.css
  public/widget/IYFwRkA/2.1.0/planner-web.d.ts
  public/widget/IYFwRkA/2.1.0/planner-web.mjs
  public/widget/IYFwRkA/2.1.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/widget.ts
Labels: C-bug

#170 fix: makes widget version in sync
  package.json
  public/widget/GYJwhgtkA/2.2.2/planner-web.css
  public/widget/GYJwhgtkA/2.2.2/planner-web.d.ts
  public/widget/GYJwhgtkA/2.2.2/planner-web.mjs
  public/widget/GYJwhgtkA/2.2.2/planner-web.umd.js
  public/widget/HYMw1kA/2.2.2/planner-web.css
  public/widget/HYMw1kA/2.2.2/planner-web.d.ts
  public/widget/HYMw1kA/2.2.2/planner-web.mjs
  public/widget/HYMw1kA/2.2.2/planner-web.umd.js
  public/widget/IYFwRkA/2.2.2/planner-web.css
  public/widget/IYFwRkA/2.2.2/planner-web.d.ts
  public/widget/IYFwRkA/2.2.2/planner-web.mjs
  public/widget/IYFwRkA/2.2.2/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-bug

#171 temp: fixes cors for temp
  middleware.js
  next.config.js
Labels: C-bug

#140 feat: disable the option to select previous dates and/or times when searching for departures.
  src/modules/search-time/selector/__tests__/selector.test.tsx
  src/modules/search-time/selector/index.tsx
Labels: C-feature

#172 fix: set height of date/time selector to fix issue in widget
  public/widget/GYJwhgtkA/2.1.0/planner-web.css
  public/widget/GYJwhgtkA/2.2.2/planner-web.css
  public/widget/HYMw1kA/2.2.2/planner-web.css
  public/widget/IYFwRkA/2.2.2/planner-web.css
  src/modules/search-time/selector/selector.module.css
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-bug

#176 temp: redirect departures
  src/pages/departures/[[...id]].tsx
Labels: C-bug

#177 fix: fix nynorsk spelling
  src/translations/components/tab-link.ts
  src/translations/pages/assistant.ts
  src/translations/pages/departures.ts
Labels: C-bug

#178 fix: trip query transferSlack and walkReluctance config
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
Labels: C-bug

#174 fix: prevent auto zoom when selecting an input field in mobile view
  src/components/search/search.tsx
Labels: C-bug

#179 feat: display both aimed start time and expected start time of departure in case of delay.
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css
Labels: C-feature

#180 feat: link to service journey details from a trip suggestion
  src/modules/cookies/index.tsx
  src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/trip-section.module.css
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/departures/details/index.tsx
  src/translations/pages/departures.ts
Labels: C-feature

#181 Revert "feat: link to service journey details from a trip suggestion …
  src/modules/cookies/index.tsx
  src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/trip-section.module.css
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/departures/details/index.tsx
  src/translations/pages/departures.ts
Labels: C-feature

#182 fix: update accessibility statement url for FRAM
  orgs/fram.json
Labels: C-bug

#184 fix: display the departure time that was expected when searching after past departures
  src/page-modules/departures/stop-place/index.tsx
Labels: C-bug

#187 feat: intermediate stops link from trip details
  src/modules/cookies/index.tsx
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/trip-section.module.css
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/departures/details/index.tsx
  src/translations/pages/departures.ts
Labels: C-feature

#185 fix: ensure that live icon and description is not rendered when displaying canceled departures.
  src/page-modules/departures/details/index.tsx
Labels: C-bug

#188 feat: get default focus point from Firebase
  src/modules/firebase/default-focus-point.ts
  src/modules/firebase/types.ts
  src/page-modules/departures/server/geocoder/index.ts
Labels: C-feature

#186 feat: reset search when switching tab
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-feature
