Repository AtB-AS/planner-web, pull requests merged in 2023-09, with the labels that each got.

#5 feat: adds example API endpoint for autocomplete
  package.json
  src/modules/api-browser/index.ts
  src/modules/api-server/index.ts
  src/modules/api-server/utils.ts
  src/page-modules/departures/client/autocomplete/index.ts
  src/page-modules/departures/client/index.ts
  src/page-modules/departures/index.ts
  src/page-modules/departures/server/autocomplete/encoders.ts
  src/page-modules/departures/server/autocomplete/index.ts
  src/page-modules/departures/server/index.ts
  src/page-modules/departures/types.ts
  src/pages/api/departures/autocomplete.ts
  src/pages/departures.tsx
  yarn.lock
Labels: C-feature

#7 fix: propagate errors
  src/modules/api-server/utils.ts
Labels: C-bug

#8 chore: adds tests as example and for plumbing different things
  package.json
  src/layouts/global-data/index.ts
  src/modules/api-server/index.ts
  src/modules/cookies/__tests__/cookies-context.test.tsx
  src/modules/cookies/cookies-context.tsx
  src/page-modules/departures/__tests__/departure.test.tsx
  src/pages/departures.tsx
  src/tests/setup.ts
  src/tests/utils.ts
  vitest.config.ts
  yarn.lock
Labels: C-chore

#10 fix: correct env variable name for test setup
  src/tests/setup.ts
Labels: C-bug

#15 feat: pass on correlation and install id from incoming request for client
  src/modules/api-server/__tests__/utils.test.ts
  src/modules/api-server/index.ts
  src/modules/api-server/utils.ts
Labels: C-feature

#12 feat: Mapbox
  .env.example
  .github/workflows/docker.yml
  Dockerfile
  package.json
  scripts/build-docker.sh
  src/components/map/index.tsx
  src/components/map/map.module.css
  src/modules/org-data/index.tsx
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/departures/server/autocomplete/index.ts
  src/page-modules/departures/types.ts
  src/pages/departures.tsx
  src/styles/globals.css
  src/tests/setup.ts
  yarn.lock
Labels: C-feature

#18 fix: docker build push deploy workflow
  .github/workflows/docker.yml
  Dockerfile
Labels: C-bug

#20 feat: button components
  src/assets/color-icon.tsx
  src/assets/utils.ts
  src/components/button/button.module.css
  src/components/button/button.tsx
  src/components/button/index.ts
  src/components/button/link.tsx
  src/components/button/utils.tsx
  src/components/loading/index.tsx
  src/components/loading/loading.module.css
  src/translations/components/index.ts
  src/translations/components/loading.ts
  src/translations/index.ts
  src/utils/css.ts
Labels: C-feature

#16 feat: adds graphql client for journey planner
  package.json
  src/modules/api-server/README.md
  src/modules/api-server/__tests__/client.test.ts
  src/modules/api-server/__tests__/utils.test.ts
  src/modules/api-server/external-client.ts
  src/modules/api-server/index.ts
  src/modules/api-server/logger.ts
  src/modules/api-server/requesters/graphql-requester.ts
  src/modules/api-server/requesters/http-requester.ts
  src/modules/api-server/requesters/log-response.ts
  src/modules/api-server/requesters/timer.ts
  src/modules/api-server/requesters/types.ts
  src/modules/api-server/requesters/utils.ts
  src/modules/api-server/utils.ts
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/departures/server/autocomplete/index.ts
  src/page-modules/departures/server/index.ts
  src/tests/utils.ts
  yarn.lock
Labels: C-feature
