Repository AtB-AS/planner-web, pull requests merged in 2024-10, with the labels that each got.

#372 feat: update travel guarantee state machine and forms
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/travel-guarantee/events.ts
  src/page-modules/contact/travel-guarantee/form-selector.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/page-modules/contact/validation/index.ts
  src/page-modules/contact/validation/special-field-validators/travelGuaranteeInputValidator.ts
  src/pages/api/contact/travel-guarantee.ts
  src/translations/pages/contact.ts
Labels: C-feature

#373 feat: update means of transport state machine and forms
  src/page-modules/contact/means-of-transport/events.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/pages/api/contact/means-of-transport.ts
  src/translations/pages/contact.ts
Labels: C-feature

#374 chore: minor improvements of FileInput component.
  src/page-modules/contact/components/input/file.tsx
  src/page-modules/contact/components/input/input.module.css
Labels: C-chore

#375 fix: consistent width of input fields in Chrome, FireFox and Safari.
  src/page-modules/contact/components/input/input.module.css
Labels: C-bug

#376 chore: add conditional validation of bankAccountNumber, IBAN and SWIFT
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-chore

#377 feat: add travel-guarantee to contact page layout
  src/page-modules/contact/layouts/contact-page-layout.tsx
Labels: C-feature

#378 feat: lost property contact page
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/lost-property/index.tsx
  src/pages/contact/lost-property.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#382 fix: hide travel guarantee forms when agreement is unchecked
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
Labels: C-bug

#379 feat: group travel contact page
  src/page-modules/contact/group-travel/group-travel-state-machine.ts
  src/page-modules/contact/group-travel/group-travel.module.css
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/server/contact/index.ts
  src/pages/api/contact/group-travel.ts
  src/pages/contact/group-travel.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#383 fix: border width of input elements
  src/page-modules/contact/components/input/input.module.css
Labels: C-bug

#384 feat: make group travel form available
  src/page-modules/contact/group-travel/group-travel.module.css
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
Labels: C-feature

#385 chore: cleanup of naming and import patterns of various page modules
  src/page-modules/contact/index.ts
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
  src/pages/contact/travel-guarantee/index.tsx
Labels: C-chore

#386 feat: extend support for vkt and farte
  .github/workflows/docker.yml
  Dockerfile
  README.md
  orgs/farte.json
  orgs/schema-validation.json
  orgs/vkt.json
  package.json
  public/telemark_fylkeskommune.svg
  public/vestfold_fylkeskommune.svg
  scripts/build-widget.sh
  scripts/build.sh
  server.js
  src/modules/org-data/index.tsx
  src/modules/theme/index.ts
  src/translations/common/layout.ts
  src/translations/common/titles.ts
  src/translations/modules/layout.ts
  yarn.lock
Labels: C-feature

#387 refactor: minor update in the organization of translation objects
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-chore

#391 feat: display public code for lines in contact form
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/server/journey-planner/index.ts
  src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
  src/page-modules/contact/server/journey-planner/validators.ts
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/utils.ts
Labels: C-feature

#392 fix: sort lines by public code
  src/page-modules/contact/server/journey-planner/index.ts
Labels: C-bug

#393 chore: generate widget version 2.27.0
  package.json
  public/widget/C4Jw9gtgzkA/2.27.0/planner-web.css
  public/widget/C4Jw9gtgzkA/2.27.0/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.27.0/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.27.0/planner-web.umd.js
  public/widget/G4awLkA/2.27.0/planner-web.css
  public/widget/G4awLkA/2.27.0/planner-web.d.ts
  public/widget/G4awLkA/2.27.0/planner-web.mjs
  public/widget/G4awLkA/2.27.0/planner-web.umd.js
  public/widget/GYJwhgtkA/2.27.0/planner-web.css
  public/widget/GYJwhgtkA/2.27.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.27.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.27.0/planner-web.umd.js
  public/widget/GYQwTgLgpkA/2.27.0/planner-web.css
  public/widget/GYQwTgLgpkA/2.27.0/planner-web.d.ts
  public/widget/GYQwTgLgpkA/2.27.0/planner-web.mjs
  public/widget/GYQwTgLgpkA/2.27.0/planner-web.umd.js
  public/widget/HYMw1kA/2.27.0/planner-web.css
  public/widget/HYMw1kA/2.27.0/planner-web.d.ts
  public/widget/HYMw1kA/2.27.0/planner-web.mjs
  public/widget/HYMw1kA/2.27.0/planner-web.umd.js
  public/widget/IYFwRkA/2.27.0/planner-web.css
  public/widget/IYFwRkA/2.27.0/planner-web.d.ts
  public/widget/IYFwRkA/2.27.0/planner-web.mjs
  public/widget/IYFwRkA/2.27.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/G4awLkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/GYQwTgLgpkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#380 feat: add tickets app page with price and tickets type form
  src/page-modules/contact/index.ts
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/validation/commonInputValidator.ts
  src/pages/api/contact/ticketing.ts
  src/pages/contact/ticketing/index.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#394 feat: searchable selector form component
  src/page-modules/contact/commoneEvents.ts
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/components/input/searchable-select/index.tsx
  src/page-modules/contact/components/input/searchable-select/utils.ts
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/events.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/utils.ts
Labels: C-feature

#398 fix: width form submit button
  src/page-modules/contact/contact.module.css
  src/page-modules/contact/group-travel/group-travel.module.css
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
Labels: C-bug

#399 chore: update components import
  src/page-modules/contact/components/form/checkbox.tsx
  src/page-modules/contact/components/form/description-modal.tsx
  src/page-modules/contact/components/form/error-message.tsx
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/components/form/index.ts
  src/page-modules/contact/components/form/input.module.css
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/form/radio.tsx
  src/page-modules/contact/components/form/searchable-select/index.tsx
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/searchable-select/utils.ts
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/contact/components/index.tsx
  src/page-modules/contact/components/input/index.ts
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
Labels: C-chore

#396 feat: ticketing app forms
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/app/index.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#400 chore: minor update of styling in contact components
  src/page-modules/contact/components/form/checkbox.tsx
  src/page-modules/contact/components/form/description-modal.tsx
  src/page-modules/contact/components/form/error-message.tsx
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/form/radio.tsx
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/components/form/textarea.tsx
Labels: C-chore

#395 feat: Upgraded design system
  next.config.js
  package.json
  src/modules/transport-mode/icon/index.tsx
  src/widget/vite.config.js
  yarn.lock
Labels: C-feature

#397 feat: ticketing webshop form
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/webshop/index.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#407 feat: add optional error message into file input component
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/components/form/form.module.css
  src/translations/pages/contact.ts
Labels: C-feature

#404 chore: minor improvements to form components
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
Labels: C-chore

#405 fix: travel guarantee - split section into two sections
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/translations/pages/contact.ts
Labels: C-bug

#401 feat: add ticketing travelcard forms
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/travel-card/index.tsx
  src/page-modules/contact/ticketing/forms/travel-card/orderTravelCardForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#403 feat: extend line filtering to filter by bus, fast ferry and ferry.
  src/page-modules/contact/commoneEvents.ts
  src/page-modules/contact/lines/use-lines.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/server/journey-planner/index.ts
  src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
  src/page-modules/contact/server/journey-planner/validators.ts
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/types.ts
  src/page-modules/contact/utils.ts
  src/translations/pages/contact.ts
Labels: C-feature

#408 fix: specify the correct sub transport modes for express boat
  src/page-modules/contact/lines/use-lines.ts
Labels: C-bug

#406 fix: add missing section in travel guarantee taxi refund form
  src/page-modules/contact/travel-guarantee/events.ts
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-bug

#411 chore: update searchable select disabled colour
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
Labels: C-chore

#412 chore: update margin of section card component
  src/page-modules/contact/components/section-card/section-card.module.css
Labels: C-chore

#415 fix: update width of submit button
  src/page-modules/contact/contact.module.css
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
Labels: C-bug

#413 feat: display contact page layout as dropdown in mobile view
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/layout.module.css
  src/translations/pages/contact.ts
Labels: C-feature

#414 fix: update the appearance of the select component
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/select.tsx
Labels: C-feature, C-bug
