Repository AtB-AS/planner-web, pull requests merged in 2024-09, with the labels that each got.

#332 feat: custom hook for lines
  src/page-modules/contact/index.ts
  src/page-modules/contact/lines/use-lines.ts
  src/page-modules/contact/server/index.ts
  src/page-modules/contact/server/journey-planner/index.ts
  src/page-modules/contact/server/journey-planner/journey-gql/lines.gql
  src/page-modules/contact/server/journey-planner/validators.ts
  src/pages/api/contact/lines.ts
Labels: C-feature

#335 feat: icons for the contact page navigator
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/layout.module.css
Labels: C-feature

#336 feat: extend the complaint form with validation of user input
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/components/input/input.tsx
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/complaint/formMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#337 chore: update logic in feedback form
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
  src/page-modules/contact/ticket-control/feedback/utils.ts
Labels: C-chore

#338 chore: update page url
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/ticket-control-page-layout.tsx
  src/pages/contact/ticket-control/complaint/index.tsx
  src/pages/contact/ticket-control/feedback/index.tsx
  src/pages/contact/ticket-control/index.tsx
Labels: C-chore

#339 feat: ticket-control api endpoint
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/server/types.ts
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
  src/pages/api/contact/ticket-control.ts
Labels: C-feature

#341 fix: inline jump bug
  src/page-modules/contact/ticket-control/ticket-control.module.css
Labels: C-bug

#343 feat: checkbox and ticket-control typo
  src/page-modules/contact/components/input/checkbox.tsx
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/components/section-card/section-card.module.css
  src/page-modules/contact/components/section-card/section-card.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/ticket-control-page-layout.tsx
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/ticket-control.module.css
  src/translations/pages/contact.ts
Labels: C-feature

#344 feat: form components and refactoring
  src/page-modules/contact/components/input/checkbox.tsx
  src/page-modules/contact/components/input/error-message.tsx
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/components/input/input.tsx
  src/page-modules/contact/components/input/radio.tsx
  src/page-modules/contact/components/input/select.tsx
  src/page-modules/contact/components/input/textarea.tsx
  src/page-modules/contact/layouts/ticket-control-page-layout.tsx
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
Labels: C-feature

#340 feat: postpone payment sub page
  src/layouts/shared/page-header.tsx
  src/page-modules/contact/formInputValidator.ts
  src/page-modules/contact/index.ts
  src/page-modules/contact/ticket-control/index.ts
  src/page-modules/contact/ticket-control/postpone-paymnet/index.tsx
  src/page-modules/contact/ticket-control/postpone-paymnet/postponePaymentFormMachine.ts
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonFieldValidator.ts
  src/page-modules/contact/validation/index.ts
  src/page-modules/contact/validation/special-field-validators/travelGuaranteeFieldValidator.ts
  src/page-modules/contact/validation/utils.ts
  src/pages/contact/index.tsx
  src/pages/contact/ticket-control/postpone-payment/index.tsx
  src/pages/contact/travel-guarantee/index.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#345 chore: update the complaint form and state machine
  src/page-modules/contact/index.ts
  src/page-modules/contact/machineEvents.ts
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/complaint/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/complaint/index.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/validation/commonFieldValidator.ts
  src/pages/contact/ticket-control/complaint/index.tsx
  src/translations/pages/contact.ts
Labels: C-chore

#346 chore: update the feedback form and state machine
  src/page-modules/contact/index.ts
  src/page-modules/contact/ticket-control/feedback/feedbackForm.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
  src/page-modules/contact/ticket-control/feedback/index.tsx
  src/page-modules/contact/validation/commonFieldValidator.ts
  src/pages/contact/ticket-control/feedback/index.tsx
Labels: C-chore

#347 feat: file attachments
  src/page-modules/contact/components/input/file.tsx
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/machineEvents.ts
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/complaint/index.tsx
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
  src/page-modules/contact/ticket-control/feedback/index.tsx
  src/page-modules/contact/utils.ts
  src/translations/pages/contact.ts
Labels: C-feature

#350 chores: divide machine events into common and form specific events.
  src/page-modules/contact/commoneEvents.ts
  src/page-modules/contact/machineEvents.ts
  src/page-modules/contact/means-of-transport/events.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/complaint/index.tsx
  src/page-modules/contact/ticket-control/events.ts
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
  src/page-modules/contact/ticket-control/feedback/index.tsx
  src/page-modules/contact/ticket-control/postpone-paymnet/index.tsx
  src/page-modules/contact/ticket-control/postpone-paymnet/postponePaymentFormMachine.ts
  src/page-modules/contact/travel-guarantee/events.ts
  src/page-modules/contact/travel-guarantee/form-selector.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/page-modules/contact/validation/index.ts
  src/page-modules/contact/validation/special-field-validators/travelGuaranteeInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-chore

#351 chore: remove unused property from form props
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
Labels: C-chore

#352 feat: error and success pages for contact page
  src/page-modules/contact/error-content/error-content.module.css
  src/page-modules/contact/error-content/error-content.tsx
  src/page-modules/contact/success-content/success-content.module.css
  src/page-modules/contact/success-content/success-content.tsx
  src/pages/contact/error.tsx
  src/pages/contact/success.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#354 fix: page header styling and contact layout
  src/layouts/shared/page-header.module.css
  src/layouts/shared/page-header.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/layout.module.css
  src/translations/pages/contact.ts
Labels: C-bug

#355 chore: update generate-assets dependency to v13.0.2
  package.json
  yarn.lock
Labels: C-chore

#353 chore: rewrite ticket control to use one state machine for all forms
  src/page-modules/contact/index.ts
  src/page-modules/contact/layouts/index.ts
  src/page-modules/contact/layouts/ticket-control-page-layout.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/ticket-control/complaint/complaintFormMachine.ts
  src/page-modules/contact/ticket-control/events.ts
  src/page-modules/contact/ticket-control/feedback/feedbackformMachine.ts
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticket-control/index.ts
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticket-control/postpone-paymnet/postponePaymentFormMachine.ts
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/form-selector.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/page-modules/contact/validation/special-field-validators/travelGuaranteeInputValidator.ts
  src/pages/contact/ticket-control/complaint/index.tsx
  src/pages/contact/ticket-control/feedback/index.tsx
  src/pages/contact/ticket-control/index.tsx
  src/pages/contact/ticket-control/postpone-payment/index.tsx
  src/translations/pages/contact.ts
Labels: C-chore

#356 chore: comment out link to contact page
  src/layouts/shared/page-header.tsx
Labels: C-chore

#357 chore: fix uncontrolled input error
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
Labels: C-bug, C-chore

#358 feat: success and error handling
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
Labels: C-feature

#361 chore: update type of prop in section card
  src/page-modules/contact/components/section-card/section-card.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/travel-guarantee/form-selector.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
Labels: C-chore

#360 feat: autocomplete help for the ticket-control form
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
Labels: C-feature

#359 fix: button display
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
Labels: C-bug

#365 fix: move bankaccount checkbox
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
Labels: C-bug

#366 fix: remove unfinished form links
  src/page-modules/contact/layouts/contact-page-layout.tsx
Labels: C-bug

#364 feat: drag and drop files
  src/page-modules/contact/components/input/file.tsx
Labels: C-feature

#367 feat: handle max file upload size
  src/page-modules/contact/components/input/file.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#370 fix: file attachment capture attribute
  src/page-modules/contact/components/input/file.tsx
Labels: C-bug

#369 fix: contact page layout responsive design
  src/page-modules/contact/layouts/layout.module.css
Labels: C-bug

#368 chore: cleanup translations
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/travel-guarantee/form-selector.tsx
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/validation/commonInputValidator.ts
  src/page-modules/contact/validation/special-field-validators/travelGuaranteeInputValidator.ts
  src/page-modules/contact/validation/utils.ts
  src/translations/pages/contact.ts
Labels: C-chore

#363 feat: display input description
  src/page-modules/contact/components/input/description-modal.tsx
  src/page-modules/contact/components/input/input.module.css
  src/page-modules/contact/components/input/input.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#371 fix: handling reseting transport mode and line.
  src/page-modules/contact/commoneEvents.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/utils.ts
Labels: C-bug
