Repository AtB-AS/planner-web, pull requests merged in 2024-12, with the labels that each got.

#460 fix: farte org data and vkt logo
  orgs/farte.json
  package.json
  public/vestfold_fylkeskommune.svg
  yarn.lock
Labels: C-bug

#461 chore: generate widget v2.36.0
  package.json
  public/widget/C4Jw9gtgzkA/2.36.0/planner-web.css
  public/widget/C4Jw9gtgzkA/2.36.0/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.36.0/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.36.0/planner-web.umd.js
  public/widget/G4awLkA/2.36.0/planner-web.css
  public/widget/G4awLkA/2.36.0/planner-web.d.ts
  public/widget/G4awLkA/2.36.0/planner-web.mjs
  public/widget/G4awLkA/2.36.0/planner-web.umd.js
  public/widget/GYJwhgtkA/2.36.0/planner-web.css
  public/widget/GYJwhgtkA/2.36.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.36.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.36.0/planner-web.umd.js
  public/widget/GYQwTgLgpkA/2.36.0/planner-web.css
  public/widget/GYQwTgLgpkA/2.36.0/planner-web.d.ts
  public/widget/GYQwTgLgpkA/2.36.0/planner-web.mjs
  public/widget/GYQwTgLgpkA/2.36.0/planner-web.umd.js
  public/widget/HYMw1kA/2.36.0/planner-web.css
  public/widget/HYMw1kA/2.36.0/planner-web.d.ts
  public/widget/HYMw1kA/2.36.0/planner-web.mjs
  public/widget/HYMw1kA/2.36.0/planner-web.umd.js
  public/widget/IYFwRkA/2.36.0/planner-web.css
  public/widget/IYFwRkA/2.36.0/planner-web.d.ts
  public/widget/IYFwRkA/2.36.0/planner-web.mjs
  public/widget/IYFwRkA/2.36.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/G4awLkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/GYQwTgLgpkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#463 fix: PostCSS processing order issue for widget
  package.json
  public/widget/C4Jw9gtgzkA/2.36.0/planner-web.css
  public/widget/G4awLkA/2.36.0/planner-web.css
  public/widget/GYJwhgtkA/2.36.0/planner-web.css
  public/widget/GYQwTgLgpkA/2.36.0/planner-web.css
  public/widget/HYMw1kA/2.36.0/planner-web.css
  public/widget/IYFwRkA/2.36.0/planner-web.css
  scripts/build-widget.sh
  src/widget/widget.module.css
  yarn.lock
Labels: C-bug

#459 chore: make radio button text more descriptive
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/translations/pages/contact.ts
Labels: C-chore

#464 feat: move form for app ticket refund to travel guarantee page
  src/page-modules/contact/index.ts
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/refund/events.ts
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/index.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/index.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/travel-guarantee/events.ts
  src/page-modules/contact/travel-guarantee/index.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/pages/api/contact/refund.ts
  src/pages/contact/refund.tsx
  src/translations/pages/contact.ts
Labels: C-feature
