Repository AtB-AS/planner-web, pull requests merged in 2024-04, with the labels that each got.

#271 chore: updates a11y statement for FRAM
  orgs/fram.json
Labels: C-chore

#272 feat: enable line filter for nfk
  .github/workflows/docker.yml
  Dockerfile
  src/page-modules/assistant/layout.tsx
Labels: C-feature

#273 fix: adds better screen reader support for loading / results states
  src/components/empty-message/index.tsx
  src/components/loading/index.tsx
  src/components/screen-reader-only/index.tsx
  src/components/screen-reader-only/screen-reader-only.module.css
  src/components/search/geolocation-button/index.tsx
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/nearest-stop-places/index.tsx
  src/page-modules/departures/stop-place/index.tsx
  src/translations/components/geolocation-button.ts
  src/translations/pages/assistant.ts
  src/translations/pages/departures.ts
Labels: C-bug

#274 fix: fixes wrong icon for GeoLocation button
  src/components/map/map.tsx
  src/components/search/geolocation-button/index.tsx
  src/widget/widget.ts
Labels: C-bug

#275 chore: updates widget to v2.15.1
  package.json
  public/widget/C4Jw9gtgzkA/2.15.1/planner-web.css
  public/widget/C4Jw9gtgzkA/2.15.1/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.15.1/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.15.1/planner-web.umd.js
  public/widget/GYJwhgtkA/2.15.1/planner-web.css
  public/widget/GYJwhgtkA/2.15.1/planner-web.d.ts
  public/widget/GYJwhgtkA/2.15.1/planner-web.mjs
  public/widget/GYJwhgtkA/2.15.1/planner-web.umd.js
  public/widget/HYMw1kA/2.15.1/planner-web.css
  public/widget/HYMw1kA/2.15.1/planner-web.d.ts
  public/widget/HYMw1kA/2.15.1/planner-web.mjs
  public/widget/HYMw1kA/2.15.1/planner-web.umd.js
  public/widget/IYFwRkA/2.15.1/planner-web.css
  public/widget/IYFwRkA/2.15.1/planner-web.d.ts
  public/widget/IYFwRkA/2.15.1/planner-web.mjs
  public/widget/IYFwRkA/2.15.1/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#277 fix: widget padding for better consumer control
  public/widget/C4Jw9gtgzkA/2.15.1/planner-web.css
  public/widget/GYJwhgtkA/2.15.1/planner-web.css
  public/widget/HYMw1kA/2.15.1/planner-web.css
  public/widget/IYFwRkA/2.15.1/planner-web.css
  src/pages/widget/index.tsx
  src/widget/widget.module.css
Labels: C-bug

#278 fix(widget): reset default fieldset padding
  package.json
  public/widget/C4Jw9gtgzkA/2.15.2/planner-web.css
  public/widget/C4Jw9gtgzkA/2.15.2/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.15.2/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.15.2/planner-web.umd.js
  public/widget/GYJwhgtkA/2.15.2/planner-web.css
  public/widget/GYJwhgtkA/2.15.2/planner-web.d.ts
  public/widget/GYJwhgtkA/2.15.2/planner-web.mjs
  public/widget/GYJwhgtkA/2.15.2/planner-web.umd.js
  public/widget/HYMw1kA/2.15.2/planner-web.css
  public/widget/HYMw1kA/2.15.2/planner-web.d.ts
  public/widget/HYMw1kA/2.15.2/planner-web.mjs
  public/widget/HYMw1kA/2.15.2/planner-web.umd.js
  public/widget/IYFwRkA/2.15.2/planner-web.css
  public/widget/IYFwRkA/2.15.2/planner-web.d.ts
  public/widget/IYFwRkA/2.15.2/planner-web.mjs
  public/widget/IYFwRkA/2.15.2/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/widget.module.css
Labels: C-bug

#279 chore: remove old patch file as it is no longer required
  patches/@github+combobox-nav+2.3.0.patch
Labels: C-chore

#268 feat: add sitemap to travel planner
  .env.example
  .github/workflows/docker.yml
  .gitignore
  Dockerfile
  README.md
  next-sitemap.js
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  orgs/troms.json
  package.json
  src/page-modules/assistant/layout.tsx
  yarn.lock
Labels: C-feature

#280 fix: remove empty lines from build script
  .github/workflows/docker.yml
Labels: C-bug

#281 fix: temporary fix to adjust for summer time
  src/utils/date.ts
Labels: C-bug

#283 fix(widget): adjust initial search time to user's local timezone
  package.json
  public/widget/C4Jw9gtgzkA/2.16.1/planner-web.css
  public/widget/C4Jw9gtgzkA/2.16.1/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.16.1/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.16.1/planner-web.umd.js
  public/widget/GYJwhgtkA/2.16.1/planner-web.css
  public/widget/GYJwhgtkA/2.16.1/planner-web.d.ts
  public/widget/GYJwhgtkA/2.16.1/planner-web.mjs
  public/widget/GYJwhgtkA/2.16.1/planner-web.umd.js
  public/widget/HYMw1kA/2.16.1/planner-web.css
  public/widget/HYMw1kA/2.16.1/planner-web.d.ts
  public/widget/HYMw1kA/2.16.1/planner-web.mjs
  public/widget/HYMw1kA/2.16.1/planner-web.umd.js
  public/widget/IYFwRkA/2.16.1/planner-web.css
  public/widget/IYFwRkA/2.16.1/planner-web.d.ts
  public/widget/IYFwRkA/2.16.1/planner-web.mjs
  public/widget/IYFwRkA/2.16.1/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/widget.ts
Labels: C-bug

#285 fix: use Troms mapbox api token and style url
  .github/workflows/docker.yml
Labels: C-bug

#284 feat: expand the search time selector to enable retrieval of search results from yesterday.
  src/modules/search-time/selector/__tests__/selector.test.tsx
  src/modules/search-time/selector/index.tsx
Labels: C-feature

#286 fix: translates a11y status texts on downshift
  src/components/search/search.tsx
  src/translations/components/index.ts
  src/translations/components/search.ts
Labels: C-bug

#288 fix: issue with default favicon being only atb
  .gitignore
  package.json
  public/favicon.ico
  yarn.lock
Labels: C-bug

#289 fix: NFK sitemap urls
  orgs/nfk.json
Labels: C-bug

#290 feat: adds open graph to address location
  src/components/map/static-map.tsx
  src/page-modules/departures/nearest-stop-places/index.tsx
  src/page-modules/departures/stop-place/index.tsx
  src/pages/api/departures/og-departure.tsx
  src/pages/api/departures/og-location.tsx
  src/pages/departures/[[...id]].tsx
  src/translations/pages/departures.ts
Labels: C-feature

#291 fix: theme color to match header for iOS safari
  src/layouts/base/index.tsx
  src/pages/api/departures/og-location.tsx
Labels: C-bug

#292 fix: add correct tickets url for nfk
  orgs/nfk.json
Labels: C-bug
