Repository AtB-AS/planner-web, pull requests merged in 2024-03, with the labels that each got.

#248 fix: improve minor styling errors in widget
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-bug

#234 feat: display departure times and search time in CET, regardless of which timezone the users is located in
  e2e-tests/assistant-search.spec.ts
  src/modules/search-time/selector/index.tsx
  src/page-modules/assistant/client/journey-planner/index.ts
  src/page-modules/assistant/details/details-header/index.tsx
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/utils/date.ts
Labels: C-feature

#250 fix: add allow url for CORS reisnordland com
  src/pages/api/departures/autocomplete.ts
Labels: C-bug

#249 chore: update widget
  package.json
  public/widget/GYJwhgtkA/2.13.0/planner-web.css
  public/widget/GYJwhgtkA/2.13.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.13.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.13.0/planner-web.umd.js
  public/widget/HYMw1kA/2.13.0/planner-web.css
  public/widget/HYMw1kA/2.13.0/planner-web.d.ts
  public/widget/HYMw1kA/2.13.0/planner-web.mjs
  public/widget/HYMw1kA/2.13.0/planner-web.umd.js
  public/widget/IYFwRkA/2.13.0/planner-web.css
  public/widget/IYFwRkA/2.13.0/planner-web.d.ts
  public/widget/IYFwRkA/2.13.0/planner-web.mjs
  public/widget/IYFwRkA/2.13.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#251 fix: enable line filter for FRAM
  .github/workflows/docker.yml
  Dockerfile
Labels: C-bug

#254 feat: extend planner-web to support Troms
  .env.example
  .github/workflows/docker.yml
  Dockerfile
  README.md
  orgs/schema-validation.json
  orgs/troms.json
  package.json
  public/troms_fylkeskommune.svg
  public/troms_fylkeskommune_dark.svg
  scripts/build-widget.sh
  scripts/build.sh
  server.js
  src/modules/org-data/index.tsx
  src/modules/theme/index.ts
  src/translations/common/layout.ts
  src/translations/common/titles.ts
  src/translations/modules/layout.ts
  yarn.lock
Labels: C-feature

#252 fix: only load map on client
  src/components/map/__tests__/map.test.tsx
  src/components/map/index.tsx
  src/components/map/map-loading.tsx
  src/components/map/map.module.css
  src/components/map/map.tsx
  src/translations/components/map.ts
Labels: C-bug

#256 fix: update search component to not cut placeholder early
  src/components/search/search.module.css
Labels: C-bug

#255 fix: update the header elements to achieve a correct sequentially-descending order
  src/layouts/shared/footer.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/layout.tsx
Labels: C-bug

#257 fix(widget): set correct line height
  src/modules/search-time/selector/selector.module.css
Labels: C-bug

#258 fix: build with dynamic import of map
  src/components/map/index.tsx
  src/components/map/map-with-header.tsx
  src/components/map/map.tsx
Labels: C-bug

#262 feat: realtime indicator for details view
  src/modules/trip-details/use-realtime-text.ts
  src/page-modules/assistant/details/trip-section/estimated-calls-section.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/realtime-section.tsx
  src/page-modules/assistant/details/trip-section/trip-section.module.css
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
Labels: C-feature

#265 chore(widget): generate widget version 2.14.0
  package.json
  public/widget/C4Jw9gtgzkA/2.14.0/planner-web.css
  public/widget/C4Jw9gtgzkA/2.14.0/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.14.0/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.14.0/planner-web.umd.js
  public/widget/GYJwhgtkA/2.14.0/planner-web.css
  public/widget/GYJwhgtkA/2.14.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.14.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.14.0/planner-web.umd.js
  public/widget/HYMw1kA/2.14.0/planner-web.css
  public/widget/HYMw1kA/2.14.0/planner-web.d.ts
  public/widget/HYMw1kA/2.14.0/planner-web.mjs
  public/widget/HYMw1kA/2.14.0/planner-web.umd.js
  public/widget/IYFwRkA/2.14.0/planner-web.css
  public/widget/IYFwRkA/2.14.0/planner-web.d.ts
  public/widget/IYFwRkA/2.14.0/planner-web.mjs
  public/widget/IYFwRkA/2.14.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#266 chore: upgrade dependencies
  package.json
  yarn.lock
Labels: C-chore

#263 fix: set filter correctly when navigating back from details page
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/trip/trip-pattern/index.tsx
Labels: C-bug

#267 fix: a11y for filter search
  src/components/labled-input/index.tsx
Labels: C-bug

#269 fix: messagebox error validity
  src/components/labled-input/index.tsx
  src/components/message-box/index.tsx
Labels: C-bug

#261 feat: extend line filtering to support nfk
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  orgs/troms.json
  src/modules/org-data/index.tsx
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/client/journey-planner/index.ts
  src/page-modules/assistant/line-filter/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/lines.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/assistant/types.ts
  src/pages/api/assistant/lines/[authorityId].ts
  src/translations/pages/assistant.ts
Labels: C-feature
