Repository AtB-AS/planner-web, pull requests merged in 2024-01, with the labels that each got.

#194 fix: widget version
  package.json
  public/widget/GYJwhgtkA/2.6.0/planner-web.css
  public/widget/GYJwhgtkA/2.6.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.6.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.6.0/planner-web.umd.js
  public/widget/HYMw1kA/2.6.0/planner-web.css
  public/widget/HYMw1kA/2.6.0/planner-web.d.ts
  public/widget/HYMw1kA/2.6.0/planner-web.mjs
  public/widget/HYMw1kA/2.6.0/planner-web.umd.js
  public/widget/IYFwRkA/2.6.0/planner-web.css
  public/widget/IYFwRkA/2.6.0/planner-web.d.ts
  public/widget/IYFwRkA/2.6.0/planner-web.mjs
  public/widget/IYFwRkA/2.6.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-bug

#191 fix: includes message from message box into buttons aria-label, to make message accessible for voiceover.
  src/components/message-box/index.tsx
Labels: C-bug

#190 feat: tariff zones in map
  package.json
  src/components/map/map.tsx
  src/components/map/use-map-tariff-zones.ts
  src/modules/firebase/index.ts
  src/utils/reference-data.ts
  yarn.lock
Labels: C-feature

#192 fix: show whole trip on map load
  src/components/map/map.tsx
  src/components/map/utils.ts
  src/page-modules/assistant/details/index.tsx
Labels: C-bug

#196 fix: fix issue with widget not selecting place
  package.json
  patches/@github+combobox-nav+2.3.0.patch
  src/widget/widget.ts
  yarn.lock
Labels: C-bug

#197 chore: update widget version (2.8.0)
  package.json
  public/widget/GYJwhgtkA/2.8.0/planner-web.css
  public/widget/GYJwhgtkA/2.8.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.8.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.8.0/planner-web.umd.js
  public/widget/HYMw1kA/2.8.0/planner-web.css
  public/widget/HYMw1kA/2.8.0/planner-web.d.ts
  public/widget/HYMw1kA/2.8.0/planner-web.mjs
  public/widget/HYMw1kA/2.8.0/planner-web.umd.js
  public/widget/IYFwRkA/2.8.0/planner-web.css
  public/widget/IYFwRkA/2.8.0/planner-web.d.ts
  public/widget/IYFwRkA/2.8.0/planner-web.mjs
  public/widget/IYFwRkA/2.8.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#201 fix: assistant details page not loading travel suggestion
  src/components/map/use-map-legs.ts
  src/components/map/use-map-tariff-zones.ts
  src/components/map/utils.ts
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
Labels: C-bug

#205 fix: improve semantics in widget
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-bug

#207 feat: debounce search when filter change
  src/modules/transport-mode/filter/__tests__/filter.test.tsx
  src/modules/transport-mode/filter/filter.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/utils.ts
Labels: C-feature

#209 fix: remove duplicate comboboxes.
  src/widget/widget.ts
Labels: C-bug

#211 feat: adds cancelled trips
  src/page-modules/assistant/details/details-header/details-header.module.css
  src/page-modules/assistant/details/details-header/index.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.test.tsx
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/trip-pattern-header.module.css
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/translations/pages/assistant.ts
Labels: C-feature

#213 chore: create widget version 2.9.0
  package.json
  public/widget/GYJwhgtkA/2.9.0/planner-web.css
  public/widget/GYJwhgtkA/2.9.0/planner-web.d.ts
  public/widget/GYJwhgtkA/2.9.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.9.0/planner-web.umd.js
  public/widget/HYMw1kA/2.9.0/planner-web.css
  public/widget/HYMw1kA/2.9.0/planner-web.d.ts
  public/widget/HYMw1kA/2.9.0/planner-web.mjs
  public/widget/HYMw1kA/2.9.0/planner-web.umd.js
  public/widget/IYFwRkA/2.9.0/planner-web.css
  public/widget/IYFwRkA/2.9.0/planner-web.d.ts
  public/widget/IYFwRkA/2.9.0/planner-web.mjs
  public/widget/IYFwRkA/2.9.0/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-feature

#212 fix: map not rendering the correct position on the departure page
  src/components/map/map.tsx
Labels: C-bug

#208 feat: configurable journey planner api configurations
  .env.example
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  src/modules/org-data/index.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
Labels: C-feature

#203 fix: make aria-labels in the search time selector visible to the screen reader
  public/widget/GYJwhgtkA/2.8.0/planner-web.mjs
  public/widget/GYJwhgtkA/2.8.0/planner-web.umd.js
  src/modules/search-time/selector/index.tsx
  src/widget/widget.ts
Labels: C-feature

#214 fix: remove duplicate aria-labelledby lables found by ARC
  src/widget/widget.ts
Labels: C-bug

#215 feat: update icon sizes
  package.json
  src/components/icon/utils.ts
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/walk-section.tsx
  src/page-modules/departures/details/index.tsx
  yarn.lock
Labels: C-feature
