Repository AtB-AS/planner-web, pull requests merged in 2024-11, with the labels that each got.

#416 chore: minor styling update for searchable selector and select
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/select.tsx
Labels: C-chore

#402 feat: add ticketing refund forms
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/refund/index.tsx
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#417 feat: custom date selector component
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/index.ts
  src/page-modules/contact/components/index.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
Labels: C-feature

#418 feat: custom time selector component
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/index.ts
  src/page-modules/contact/components/form/time-selector.tsx
  src/page-modules/contact/components/index.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
Labels: C-feature

#423 chore: add max width to submit button
  src/page-modules/contact/contact.module.css
Labels: C-chore

#421 feat: add link to ticketing forms
  src/page-modules/contact/layouts/contact-page-layout.tsx
Labels: C-feature

#422 chore: update input label property type
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/group-travel/index.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/travel-card/orderTravelCardForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
Labels: C-chore

#419 chore: update translations
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/translations/pages/contact.ts
Labels: C-chore

#428 feat: reorganize display of bank account input fields
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
Labels: C-feature

#425 feat: extend input component with disabled property
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/input.tsx
Labels: C-feature

#430 fix: undo unintended removal of input field
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
Labels: C-bug

#429 feat: extend selector label to better illustrate when the selector is disabled
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/select.tsx
Labels: C-feature

#420 feat: extend description mode with list and instruction properties
  src/page-modules/contact/components/form/description-modal.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/index.ts
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/index.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/refund/appTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/refund/otherTicketRefund.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#431 feat: link to contact form
  orgs/fram.json
  src/translations/modules/layout.ts
Labels: C-feature

#433 feat: set the date of the incident manually
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/group-travel/group-travel-state-machine.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
  src/page-modules/contact/travel-guarantee/travelGuaranteeFormMachine.ts
  src/page-modules/contact/utils.ts
Labels: C-feature

#426 feat: add styling to highlight whenever the searchable selector is disabled
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
Labels: C-feature

#434 fix: remove property area from contact forms
  src/page-modules/contact/means-of-transport/events.ts
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-bug

#435 feat: extend the group travel page with both date and time selector
  src/page-modules/contact/group-travel/group-travel-state-machine.ts
  src/page-modules/contact/group-travel/index.tsx
Labels: C-feature

#436 fix: remove redundant fallback value
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundCarForm.tsx
  src/page-modules/contact/travel-guarantee/forms/refundTaxiForm.tsx
Labels: C-bug

#437 fix: remove validation message when toggling between the input fields
  src/page-modules/contact/utils.ts
Labels: C-bug

#439 fix: add condition to avoid runtime error
  src/page-modules/contact/components/form/time-selector.tsx
Labels: C-bug

#438 fix: update translations of date and time properties in ticket control state machine
  src/page-modules/contact/ticket-control/events.ts
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-bug

#440 fix: translation typo
  src/translations/pages/contact.ts
Labels: C-bug

#441 fix: translation typos
  src/translations/pages/contact.ts
Labels: C-bug

#443 fix: ensure that only situations within valid periods are displayed
  src/modules/situations/__tests__/stop-place.test.tsx
  src/modules/situations/utils.ts
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/departures/stop-place/index.tsx
Labels: C-bug

#445 fix: update attachments to be optional in app forms
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
Labels: C-bug

#446 feat: update translation text in lost property page
  src/page-modules/contact/lost-property/index.tsx
  src/translations/pages/contact.ts
Labels: C-feature

#448 feat: replace form for ordering travel card with link to webshop
  src/page-modules/contact/ticketing/forms/travel-card/index.tsx
  src/page-modules/contact/ticketing/forms/travel-card/orderTravelCard.tsx
  src/page-modules/contact/ticketing/forms/travel-card/orderTravelCardForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#449 fix: add bullet points to detail list
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/translations/pages/contact.ts
Labels: C-bug

#450 feat: upgrade colour theme to version 11.2.0
  package.json
  yarn.lock
Labels: C-feature

#452 feat: add links for Telemark
  orgs/vkt.json
Labels: C-feature

#453 fix: ensure that situation icons are only displayed during the validity period
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
Labels: C-bug

#442 fix: make fromStop and toStop input fields optional in ticket control feedback form
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/translations/pages/contact.ts
Labels: C-bug

#455 fix: situations for assistant page
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
Labels: C-bug

#451 feat: Removed legacy theme structure
  next.config.js
  package.json
  src/components/icon/mono-icon.tsx
  src/modules/theme/index.ts
  yarn.lock
Labels: C-feature

#456 chore: upgrade assets and theme packages
  package.json
  yarn.lock
Labels: C-chore

#458 style: remove excessive padding around list
  src/page-modules/contact/contact.module.css
Labels: C-chore

#457 fix: add a new exception to travelguarantee
  src/page-modules/contact/travel-guarantee/index.tsx
  src/translations/pages/contact.ts
Labels: C-chore

#454 fix: avoid opening new tab when clicking on link to contact form
  src/layouts/shared/footer.tsx
Labels: C-bug
