Repository AtB-AS/planner-web, pull requests merged in 2024-06, with the labels that each got.

#297 feat: global messages context provider
  src/modules/global-messages/converters.ts
  src/modules/global-messages/index.tsx
  src/modules/global-messages/types.ts
Labels: C-feature

#302 fix: let header image navigate to main page
  src/layouts/shared/page-header.tsx
  src/translations/common/layout.ts
Labels: C-bug

#304 feat: troms configuration
  .github/workflows/docker.yml
  orgs/troms.json
  package.json
  src/translations/common/titles.ts
  src/translations/modules/layout.ts
  yarn.lock
Labels: C-feature

#299 fix: fix server side redirect error
  src/page-modules/assistant/layout.tsx
Labels: C-bug

#303 feat: display global messages
  src/components/message-box/index.tsx
  src/layouts/default.tsx
  src/layouts/shared/home-link-with-global-message-layout.module.css
  src/layouts/shared/home-link-with-global-message-layout.tsx
  src/modules/global-messages/context.tsx
  src/modules/global-messages/global-messages.module.css
  src/modules/global-messages/global-messages.tsx
  src/modules/global-messages/index.ts
  src/modules/global-messages/types.ts
  src/modules/search-time/selector/index.tsx
  src/modules/search-time/selector/selector.module.css
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/departures.module.css
  src/page-modules/departures/layout.tsx
Labels: C-feature

#306 feat: updates dependencies and theme message box
  package.json
  patches/@github+combobox-nav+3.0.1.patch
  src/components/message-box/index.tsx
  src/components/message-box/message-box.module.css
  yarn.lock
Labels: C-feature

#305 feat: adds maximum interchange wait time to details page. Fixes #18410
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/interchange-section.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/translations/pages/assistant.ts
Labels: C-feature

#308 fix: show correct day label for trip results
  src/page-modules/assistant/trip/index.tsx
Labels: C-bug

#309 chore: upgrade theme and assets packages
  package.json
  src/components/tab-link/tab-link.module.css
  src/modules/transport-mode/filter/filter.module.css
  yarn.lock
Labels: C-chore

#310 fix: footer content for Svipper
  orgs/troms.json
  src/translations/modules/layout.ts
Labels: C-bug
