Repository AtB-AS/planner-web, pull requests merged in 2024-08, with the labels that each got.

#313 fix: display departures in CET instead of local time
  src/utils/date.ts
Labels: C-bug

#314 chore: upgrades dependencies (2024-08-01)
  Dockerfile
  package.json
  src/components/button/utils.tsx
  src/components/map/use-map-interactions.ts
  yarn.lock
Labels: C-chore

#315 chore: generate widget version 2.21.1
  package.json
  public/widget/C4Jw9gtgzkA/2.21.1/planner-web.css
  public/widget/C4Jw9gtgzkA/2.21.1/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/2.21.1/planner-web.mjs
  public/widget/C4Jw9gtgzkA/2.21.1/planner-web.umd.js
  public/widget/GYJwhgtkA/2.21.1/planner-web.css
  public/widget/GYJwhgtkA/2.21.1/planner-web.d.ts
  public/widget/GYJwhgtkA/2.21.1/planner-web.mjs
  public/widget/GYJwhgtkA/2.21.1/planner-web.umd.js
  public/widget/HYMw1kA/2.21.1/planner-web.css
  public/widget/HYMw1kA/2.21.1/planner-web.d.ts
  public/widget/HYMw1kA/2.21.1/planner-web.mjs
  public/widget/HYMw1kA/2.21.1/planner-web.umd.js
  public/widget/IYFwRkA/2.21.1/planner-web.css
  public/widget/IYFwRkA/2.21.1/planner-web.d.ts
  public/widget/IYFwRkA/2.21.1/planner-web.mjs
  public/widget/IYFwRkA/2.21.1/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
Labels: C-chore

#317 feat: changes time and date input to react-aria
  package.json
  src/modules/search-time/selector/__tests__/selector.test.tsx
  src/modules/search-time/selector/index.tsx
  src/modules/search-time/selector/selector.module.css
  src/modules/search-time/selector/time-selector.tsx
  yarn.lock
Labels: C-feature

#319 fix: add svipper links
  orgs/troms.json
Labels: C-bug

#320 feat: extend notices to inform users about the need to contact the relevant authorities to carry out certain trips
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/validators.ts
Labels: C-feature

#321 feat: mapbox api token staging for fram
  .github/workflows/docker.yml
Labels: C-feature

#318 feat: changes date input to use react-aria
  src/layouts/base/index.tsx
  src/layouts/default.tsx
  src/modules/search-time/selector/__tests__/selector.test.tsx
  src/modules/search-time/selector/date-selector.tsx
  src/modules/search-time/selector/index.tsx
  src/modules/search-time/selector/selector.module.css
Labels: C-feature

#326 feat: show destination display via information
  src/page-modules/departures/__tests__/departure-data.fixture.ts
  src/page-modules/departures/__tests__/departure-details.test.tsx
  src/page-modules/departures/__tests__/service-journey-data.fixture.ts
  src/page-modules/departures/details/index.tsx
  src/page-modules/departures/server/journey-planner/index.ts
  src/page-modules/departures/server/journey-planner/journey-gql/departures.gql
  src/page-modules/departures/server/journey-planner/journey-gql/estimated-calls.gql
  src/page-modules/departures/server/journey-planner/journey-gql/service-journey-with-estimated-calls.gql
  src/page-modules/departures/server/journey-planner/validators.ts
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/utils.ts
  src/translations/dictionary.ts
Labels: C-feature

#323 feat: create page for contact schema with feature flag
  src/layouts/shared/page-header.module.css
  src/layouts/shared/page-header.tsx
  src/modules/org-data/index.tsx
  src/page-modules/contact/index.ts
  src/page-modules/contact/layout.tsx
  src/page-modules/contact/utils.ts
  src/pages/contact/index.tsx
  src/translations/common/layout.ts
Labels: C-feature

#327 feat: add logic to interact with with contact api.
  src/modules/api-server/requesters/types.ts
  src/page-modules/contact/content/content.module.css
  src/page-modules/contact/content/index.tsx
  src/page-modules/contact/server/contact/index.ts
  src/page-modules/contact/server/index.ts
  src/page-modules/contact/server/types.ts
  src/page-modules/contact/utils.ts
  src/pages/api/contact/index.ts
  src/pages/contact/index.tsx
Labels: C-feature

#328 feat: add categorySelector and add ticket control and fee page
  src/page-modules/contact/index.ts
  src/page-modules/contact/layout.tsx
  src/page-modules/contact/layout/contact-page-navigator.tsx
  src/page-modules/contact/layout/index.ts
  src/page-modules/contact/layout/layout.module.css
  src/page-modules/contact/layout/layout.tsx
  src/page-modules/contact/ticket-control-and-fee/index.tsx
  src/page-modules/contact/ticket-control-and-fee/ticket-control-and-fee.module.css
  src/pages/contact/billettkontroll-og-gebyr/index.tsx
  src/pages/contact/index.tsx
  src/translations/pages/contact.ts
  src/translations/pages/index.ts
Labels: C-feature

#329 chore: add initialize map log event
  src/components/map/map.tsx
  src/modules/firebase/analytics.ts
Labels: C-chore

#331 feat: add contact section card component
  src/page-modules/contact/components/section-card/index.ts
  src/page-modules/contact/components/section-card/section-card.module.css
  src/page-modules/contact/components/section-card/section-card.tsx
Labels: C-feature
