Repository AtB-AS/planner-web, pull requests merged in 2024-02, with the labels that each got.

#220 feat: ticket information url in footer
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  src/layouts/shared/footer.tsx
  src/modules/org-data/index.tsx
  src/translations/modules/layout.ts
Labels: C-feature

#219 fix: increase the contrast between placeholder text and the background
  src/components/search/search.module.css
  src/widget/widget.module.css
Labels: C-bug

#224 fix: journey planner API config for FRAM and NFK
  orgs/fram.json
  orgs/nfk.json
Labels: C-bug

#218 fix: consistant departure time logic and no realtime on cancellation
  src/components/departure-time/__tests__/departure-time.test.tsx
  src/components/departure-time/departure-time.module.css
  src/components/departure-time/index.tsx
  src/components/typography/index.tsx
  src/modules/time-representation/index.ts
  src/modules/trip-details/departure-time/index.tsx
  src/modules/trip-details/index.ts
  src/modules/trip-details/use-realtime-text.ts
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/page-modules/departures/details/estimated-call-rows.tsx
  src/page-modules/departures/details/index.tsx
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/stop-place/stop-place.module.css
  src/tests/global-setup.ts
  src/translations/components/departure-time.ts
  src/translations/components/index.ts
  src/translations/pages/departures.ts
  vitest.config.ts
Labels: C-feature, C-bug

#225 feat: adds realtime indicator to departures
  src/components/departure-time/__tests__/departure-time.test.tsx
  src/components/departure-time/departure-time.module.css
  src/components/departure-time/index.tsx
  src/page-modules/departures/__tests__/departure-data.fixture.ts
  src/page-modules/departures/server/journey-planner/index.ts
  src/page-modules/departures/server/journey-planner/validators.ts
  src/page-modules/departures/stop-place/index.tsx
Labels: C-feature

#223 chore: adds initial e2e case
  .github/workflows/playwright-scheduled-staging.yml
  .github/workflows/playwright.yml
  .gitignore
  e2e-tests/search-test.spec.ts
  package.json
  playwright.config.ts
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  vitest.config.ts
  yarn.lock
Labels: C-chore

#226 fix: filter out locations where locality is undefined from the travel planner's input field.
  src/components/search/search.tsx
  src/page-modules/departures/server/geocoder/index.ts
  src/page-modules/departures/types.ts
Labels: C-bug

#202 feat: adding the option to include via location when searching after a trip.
  src/components/search/clear-button/index.tsx
  src/components/search/index.ts
  src/modules/transport-mode/filter/filter.tsx
  src/page-modules/assistant/__tests__/assistant-data.fixture.ts
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/via-trip-with-details.gql
  src/page-modules/assistant/server/journey-planner/journey-gql/via-trip.gql
  src/page-modules/assistant/trip-query-fetcher.ts
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/assistant/trip/trip.module.css
  src/page-modules/assistant/types.ts
  src/page-modules/assistant/utils.ts
  src/pages/api/assistant/trip.ts
  src/translations/components/clear-button.ts
  src/translations/components/index.ts
  src/translations/pages/assistant.ts
Labels: C-feature

#228 chore: adds cache for e2e tests
  .github/workflows/playwright-scheduled-staging.yml
  .github/workflows/playwright.yml
Labels: C-chore

#227 feat: line filter in search
  orgs/atb.json
  orgs/fram.json
  orgs/nfk.json
  orgs/schema-validation.json
  src/modules/org-data/index.tsx
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/line-filter/index.tsx
  src/page-modules/assistant/line-filter/line-filter.module.css
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/server/journey-planner/journey-gql/trip.gql
  src/page-modules/assistant/trip-query-fetcher.ts
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/assistant/types.ts
  src/page-modules/assistant/utils.ts
  src/pages/api/assistant/trip.ts
  src/translations/pages/assistant.ts
Labels: C-feature

#235 chore: updates dependencies
  package.json
  patches/@github+combobox-nav+2.3.1.patch
  src/components/map/use-map-tariff-zones.ts
  src/modules/firebase/types.ts
  src/utils/date.ts
  vitest.config.ts
  yarn.lock
Labels: C-chore

#239 fix: details page for trip search with line filter
  src/page-modules/assistant/server/journey-planner/journey-gql/trip-with-details.gql
Labels: C-bug

#232 fix: automatically resets to the current date if the current month or current year is reselected twice.
  src/modules/search-time/selector/index.tsx
Labels: C-bug

#241 feat: feature flag for diasbling line filter
  .github/workflows/docker.yml
  Dockerfile
  src/page-modules/assistant/layout.tsx
Labels: C-feature

#242 feat: disable travel planner flight filter by default
  src/modules/transport-mode/filter/__tests__/filter.test.tsx
  src/modules/transport-mode/filter/filter.tsx
  src/page-modules/assistant/layout.tsx
Labels: C-feature

#245 fix: fix bug with query param in widget
  package.json
  public/widget/GYJwhgtkA/2.12.1/planner-web.css
  public/widget/GYJwhgtkA/2.12.1/planner-web.d.ts
  public/widget/GYJwhgtkA/2.12.1/planner-web.mjs
  public/widget/GYJwhgtkA/2.12.1/planner-web.umd.js
  public/widget/HYMw1kA/2.12.1/planner-web.css
  public/widget/HYMw1kA/2.12.1/planner-web.d.ts
  public/widget/HYMw1kA/2.12.1/planner-web.mjs
  public/widget/HYMw1kA/2.12.1/planner-web.umd.js
  public/widget/IYFwRkA/2.12.1/planner-web.css
  public/widget/IYFwRkA/2.12.1/planner-web.d.ts
  public/widget/IYFwRkA/2.12.1/planner-web.mjs
  public/widget/IYFwRkA/2.12.1/planner-web.umd.js
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/widget.ts
Labels: C-bug

#236 fix: update button style in widget to match button in travel planner when fram is the organization.
  src/components/button/button.module.css
  src/widget/vite.config.js
  src/widget/widget.module.css
  src/widget/widget.ts
Labels: C-bug

#246 fix(widget): fix bug with altered href
  public/widget/GYJwhgtkA/2.12.1/planner-web.css
  public/widget/GYJwhgtkA/2.12.1/planner-web.mjs
  public/widget/GYJwhgtkA/2.12.1/planner-web.umd.js
  public/widget/HYMw1kA/2.12.1/planner-web.css
  public/widget/HYMw1kA/2.12.1/planner-web.mjs
  public/widget/HYMw1kA/2.12.1/planner-web.umd.js
  public/widget/IYFwRkA/2.12.1/planner-web.css
  public/widget/IYFwRkA/2.12.1/planner-web.mjs
  public/widget/IYFwRkA/2.12.1/planner-web.umd.js
  src/widget/widget.ts
Labels: C-bug

#244 chore: trigger playwright on deployment state
  .github/workflows/playwright.yml
Labels: C-chore

#247 chore: trying to avoid issue with cached results in e2e tests
  e2e-tests/assistant-view.spec.ts
Labels: C-chore
