Repository AtB-AS/planner-web, pull requests merged in 2025-05, with the labels that each got.

#537 fix: update to use correct input type
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
Labels: C-bug

#539 feat: automatic focus on the first form error message
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/means-of-transport/events.ts
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/means-of-transport/index.tsx
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
  src/page-modules/contact/refund/events.ts
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/refund/index.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
  src/page-modules/contact/ticket-control/events.ts
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticket-control/index.tsx
  src/page-modules/contact/ticket-control/ticket-control-form-machine.ts
  src/page-modules/contact/ticketing/events.ts
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/ticketing/index.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/page-modules/contact/utils.ts
Labels: C-feature

#538 feat: id property to textarea component
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
Labels: C-feature

#540 feat: add id property to select component
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
Labels: C-feature

#546 feat: extend textarea component in contact from
  src/page-modules/contact/components/form/fieldset/fieldset.module.css
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
Labels: C-feature

#543 feat: add id tag to time selector component in contact form
  src/page-modules/contact/components/form/time-selector.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/utils.ts
Labels: C-feature

#544 fix: validation error caused by wrong input types in contact form
  src/page-modules/contact/refund/events.ts
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/page-modules/contact/types.ts
  src/page-modules/contact/validation/validationRules.ts
  src/translations/pages/contact.ts
Labels: C-bug

#548 feat: add required indicator to contact form components
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/components/form/form-component-label/form-component-label.module.css
  src/page-modules/contact/components/form/form-component-label/index.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/components/form/time-selector.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticket-control/forms/postponePayment.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
Labels: C-feature

#552 fix: Fixed swapped lat/lon for autocomplete
  src/page-modules/departures/client/geocoder/index.ts
Labels: C-bug

#551 fix: Update widget texts
  package.json
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.css
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.d.ts
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.mjs
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.umd.js
  public/widget/G4awLkA/3.0.1/planner-web.css
  public/widget/G4awLkA/3.0.1/planner-web.d.ts
  public/widget/G4awLkA/3.0.1/planner-web.mjs
  public/widget/G4awLkA/3.0.1/planner-web.umd.js
  public/widget/GYJwhgtkA/3.0.1/planner-web.css
  public/widget/GYJwhgtkA/3.0.1/planner-web.d.ts
  public/widget/GYJwhgtkA/3.0.1/planner-web.mjs
  public/widget/GYJwhgtkA/3.0.1/planner-web.umd.js
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.css
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.d.ts
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.mjs
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.umd.js
  public/widget/HYMw1kA/3.0.1/planner-web.css
  public/widget/HYMw1kA/3.0.1/planner-web.d.ts
  public/widget/HYMw1kA/3.0.1/planner-web.mjs
  public/widget/HYMw1kA/3.0.1/planner-web.umd.js
  public/widget/IYFwRkA/3.0.1/planner-web.css
  public/widget/IYFwRkA/3.0.1/planner-web.d.ts
  public/widget/IYFwRkA/3.0.1/planner-web.mjs
  public/widget/IYFwRkA/3.0.1/planner-web.umd.js
  src/page-modules/widget/available-widgets/C4Jw9gtgzkA/manifest.json
  src/page-modules/widget/available-widgets/G4awLkA/manifest.json
  src/page-modules/widget/available-widgets/GYJwhgtkA/manifest.json
  src/page-modules/widget/available-widgets/GYQwTgLgpkA/manifest.json
  src/page-modules/widget/available-widgets/HYMw1kA/manifest.json
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/widget.ts
Labels: C-bug

#547 fix: validation errors in contact form
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/ticketing/ticketingStateMachine.ts
  src/page-modules/contact/validation/validationRules.ts
  src/translations/pages/contact.ts
Labels: C-bug

#556 fix: rounded top border for destination input
  src/page-modules/assistant/assistant.module.css
Labels: C-bug

#549 chore: update assets package to latest
  package.json
  yarn.lock
Labels: C-chore

#550 feat: move situation/notice icons and rail replacement bus icons
  src/modules/situations/situation-or-notice-icon.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/rail-replacement-bus.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/trip-pattern-header.module.css
Labels: C-feature

#558 feat: update link to contact form
  src/layouts/shared/footer.tsx
Labels: C-feature

#559 fix: contact form translations
  src/translations/pages/contact.ts
Labels: C-bug

#561 feat: extend customer number description to include number of digits
  src/translations/pages/contact.ts
Labels: C-feature

#563 fix: add alt text for situation and notice icons
  src/modules/situations/situation-or-notice-icon.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
Labels: C-bug, TPW

#557 chore: Update theme
  package.json
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.css
  public/widget/G4awLkA/3.0.1/planner-web.css
  public/widget/GYJwhgtkA/3.0.1/planner-web.css
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.css
  public/widget/HYMw1kA/3.0.1/planner-web.css
  public/widget/IYFwRkA/3.0.1/planner-web.css
  yarn.lock
Labels: C-chore

#568 feat: enable automatic scroll to error message for file-input component
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/means-of-transport/forms/delayForm.tsx
  src/page-modules/contact/means-of-transport/forms/driverForm.tsx
  src/page-modules/contact/means-of-transport/forms/injuryForm.tsx
  src/page-modules/contact/means-of-transport/forms/serviceOfferingForm.tsx
  src/page-modules/contact/means-of-transport/forms/stopForm.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
  src/page-modules/contact/ticketing/forms/app/appAccountForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTicketingForm.tsx
  src/page-modules/contact/ticketing/forms/app/appTravelSuggestionForm.tsx
  src/page-modules/contact/ticketing/forms/priceAndTicketTypesForm.tsx
  src/page-modules/contact/ticketing/forms/travel-card/travelCardQuestionForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopAccountForm.tsx
  src/page-modules/contact/ticketing/forms/webshop/webshopTicketingForm.tsx
  src/page-modules/contact/utils.ts
Labels: C-feature

#566 feat: remove page selector from contact page layout
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/layout.module.css
  src/translations/pages/contact.ts
Labels: C-feature

#569 Small fixes for colors
  package.json
  src/layouts/base/index.tsx
  src/modules/search-time/selector/selector.module.css
  src/utils/org-theme-definitions.ts
  yarn.lock
Labels: C-bug

#570 feat: add refund carnet ticket translation to contact form
  src/translations/pages/contact.ts
Labels: C-feature

#571 feat: improve fieldset spacing and padding in contact form
  src/page-modules/contact/components/form/fieldset/fieldset.module.css
  src/page-modules/contact/contact.module.css
  src/page-modules/contact/layouts/layout.module.css
Labels: C-feature

#573 Revert "chore: Update theme (#557)"
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.css
  public/widget/G4awLkA/3.0.1/planner-web.css
  public/widget/GYJwhgtkA/3.0.1/planner-web.css
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.css
  public/widget/HYMw1kA/3.0.1/planner-web.css
  public/widget/IYFwRkA/3.0.1/planner-web.css
Labels: C-chore

#574 fix: Adds rebuilt widget-commit to main
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.css
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.mjs
  public/widget/C4Jw9gtgzkA/3.0.1/planner-web.umd.js
  public/widget/G4awLkA/3.0.1/planner-web.css
  public/widget/G4awLkA/3.0.1/planner-web.mjs
  public/widget/G4awLkA/3.0.1/planner-web.umd.js
  public/widget/GYJwhgtkA/3.0.1/planner-web.css
  public/widget/GYJwhgtkA/3.0.1/planner-web.mjs
  public/widget/GYJwhgtkA/3.0.1/planner-web.umd.js
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.css
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.mjs
  public/widget/GYQwTgLgpkA/3.0.1/planner-web.umd.js
  public/widget/HYMw1kA/3.0.1/planner-web.css
  public/widget/HYMw1kA/3.0.1/planner-web.mjs
  public/widget/HYMw1kA/3.0.1/planner-web.umd.js
  public/widget/IYFwRkA/3.0.1/planner-web.css
  public/widget/IYFwRkA/3.0.1/planner-web.mjs
  public/widget/IYFwRkA/3.0.1/planner-web.umd.js
Labels: C-bug

#567 feat: Time Picker
  src/modules/search-time/selector/index.tsx
  src/modules/search-time/selector/selector.module.css
  src/modules/search-time/selector/time-selector-dropdown.module.css
  src/modules/search-time/selector/time-selector-dropdown.tsx
  src/modules/search-time/selector/time-selector.tsx
Labels: C-feature

#577 feat: Auto-move time to early morning on date change away from today
  src/modules/search-time/selector/index.tsx
Labels: C-feature

#578 fix: keep loading indicator when yet to get results
  src/page-modules/assistant/client/journey-planner/index.ts
  src/page-modules/assistant/trip/index.tsx
Labels: C-bug

#580 fix: don't revalidate trip pattern fetching
  src/page-modules/assistant/client/journey-planner/index.ts
Labels: C-bug

#583 fix: use same search config values as the app
  src/page-modules/assistant/client/journey-planner/index.ts
Labels: C-bug

#586 test: open accordion and then details
  e2e-tests/k6/conf/env.ts
  e2e-tests/k6/measurements/measures.ts
  e2e-tests/k6/measurements/metrics.ts
  e2e-tests/k6/pages/assistant.ts
  e2e-tests/k6/scenario/assistant.ts
  src/page-modules/assistant/trip/trip-pattern/index.tsx
Labels: test

#585 feat: load more until new results
  src/page-modules/assistant/client/journey-planner/index.ts
Labels: C-feature
