Repository AtB-AS/planner-web, pull requests merged in 2025-08, with the labels that each got.

#600 fix: Decreased the threshold for significant difference
  src/components/departure-time/__tests__/departure-time.test.tsx
  src/modules/time-representation/index.ts
Labels: C-bug

#611 feat: extend textarea component with required indicator.
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
Labels: C-feature

#607 fix: Double load problem when navigating from widget
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/client/journey-planner/index.ts
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/trip/index.tsx
  src/pages/assistant/index.tsx
  src/tests/setup.ts
Labels: C-bug

#603 fix: Retain via and line number when navigating back
  src/modules/logging/log-page-access.ts
  src/page-modules/assistant/details-body/index.tsx
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/details/utils.ts
Labels: C-bug

#619 chore: upgrades dependencies (2025-08-14)
  package.json
  src/components/button/button.tsx
  src/components/button/link.tsx
  src/components/icon/color-icon.tsx
  src/components/icon/illustration.tsx
  src/components/icon/image.tsx
  src/components/icon/mono-icon.tsx
  src/components/labled-input/index.tsx
  src/components/loading-empty-results/index.tsx
  src/components/map/map.tsx
  src/components/map/use-map-tariff-zones.ts
  src/components/message-box/index.tsx
  src/components/screen-reader-only/index.tsx
  src/modules/cookies/cookies-context.tsx
  src/modules/search-time/selector/date-selector.tsx
  src/modules/search-time/selector/time-selector.tsx
  src/modules/transport-mode/types.ts
  src/page-modules/assistant/line-filter/index.tsx
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/components/form/description-modal.tsx
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/form/radio.tsx
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/departures/details/estimated-call-rows.tsx
  yarn.lock
Labels: C-chore, TPW, :wrench: Maintenance

#624 fix(contact): support 8 digit customer numbers
  src/page-modules/contact/validation/validationRules.ts
  src/translations/pages/contact.ts
Labels: C-bug

#625 fix: typo in contact form
  src/translations/pages/contact.ts
Labels: C-bug

#628 feat: improve changing of orgs
  package.json
  yarn.lock
Labels: C-feature

#630 fix: Fixed very tiny travel suggestions
  src/page-modules/assistant/assistant.module.css
Labels: C-bug
