Repository AtB-AS/planner-web, pull requests merged in 2025-01, with the labels that each got.

#468 fix: ensure case-insensitive matching of selected IDs in custom selector
  src/page-modules/contact/components/form/select.tsx
Labels: C-bug

#470 feat: add refund reason to appTicketRefund form
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
Labels: C-feature

#471 feat: force Farte light theme
  .env.example
  orgs/farte.json
  orgs/schema-validation.json
  src/layouts/shared/footer.tsx
  src/modules/org-data/index.tsx
  src/modules/theme/index.ts
  src/translations/modules/layout.ts
Labels: C-feature

#472 fix: specify post body size limit for contact form api
  src/pages/api/contact/contact-api-config.ts
  src/pages/api/contact/means-of-transport.ts
  src/pages/api/contact/refund.ts
  src/pages/api/contact/ticket-control.ts
  src/pages/api/contact/ticketing.ts
Labels: C-bug

#473 feat: quay public code prefix
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/details/trip-section/index.tsx
  src/page-modules/assistant/details/trip-section/interchange-section.tsx
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/page-modules/departures/details/estimated-call-rows.tsx
  src/page-modules/departures/details/utils.ts
  src/page-modules/departures/stop-place/index.tsx
  src/translations/dictionary.ts
  src/translations/pages/assistant.ts
  src/translations/pages/departures.ts
Labels: C-feature, C-bug

#474 feat: add page with link to form for retrieving residual value on travel cards
  src/page-modules/contact/refund/forms/residualValueOnTravelCard/index.tsx
  src/page-modules/contact/refund/index.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
  src/translations/pages/contact.ts
Labels: C-feature

#475 fix: correct typo and conditional render correct header when forced theme
  src/layouts/shared/footer.tsx
  src/translations/modules/layout.ts
Labels: C-bug

#477 feat: update org-specific ticket message and line number hint
  src/translations/pages/assistant.ts
  src/translations/server/endpoints.ts
Labels: C-feature

#478 fix: update config for contact api endpoints
  src/pages/api/contact/contact-api-config.ts
  src/pages/api/contact/means-of-transport.ts
  src/pages/api/contact/refund.ts
  src/pages/api/contact/ticket-control.ts
  src/pages/api/contact/ticketing.ts
Labels: C-bug

#476 fix: nynorsk typos
  src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.test.tsx
  src/translations/components/geolocation-button.ts
  src/translations/pages/assistant.ts
  src/translations/pages/contact.ts
Labels: C-bug

#479 feat: more global messages contexts
  src/components/message-box/index.tsx
  src/components/message-box/message-box.module.css
  src/modules/global-messages/context.tsx
  src/modules/global-messages/global-messages.tsx
  src/modules/global-messages/types.ts
  src/page-modules/assistant/details/details.module.css
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/__tests__/departure-details.test.tsx
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/departures/details/index.tsx
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/stop-place/stop-place.module.css
Labels: C-feature

#480 test: performance test with k6
  e2e-tests/k6/.gitignore
  e2e-tests/k6/README.md
  e2e-tests/k6/conf/conf.ts
  e2e-tests/k6/conf/env.ts
  e2e-tests/k6/conf/options.ts
  e2e-tests/k6/data/locations.ts
  e2e-tests/k6/measurements/measures.ts
  e2e-tests/k6/measurements/metrics.ts
  e2e-tests/k6/package.json
  e2e-tests/k6/pages/assistant.ts
  e2e-tests/k6/pages/departures.ts
  e2e-tests/k6/runTest.ts
  e2e-tests/k6/scenario/assistant.ts
  e2e-tests/k6/scenario/departures.ts
  e2e-tests/k6/scenario/scenario.ts
  e2e-tests/k6/types/index.ts
  e2e-tests/k6/utils/utils.ts
  e2e-tests/k6/yarn.lock
  src/components/search/search.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/layout.tsx
  src/page-modules/departures/stop-place/index.tsx
  tsconfig.json
Labels: test

#481 feat: time-specific and dismissable global messages
  src/components/message-box/index.tsx
  src/components/message-box/message-box.module.css
  src/modules/global-messages/context.tsx
  src/modules/global-messages/global-messages.tsx
  src/utils/use-interval.ts
  src/utils/use-localstorage.ts
  src/utils/use-now.ts
Labels: C-feature

#482 fix: disallow robots in non-production
  next-sitemap.js
Labels: C-bug

#484 fix: Fixed too strict zod-schema for global messages
  src/modules/global-messages/types.ts
Labels: C-bug

#483 feat: Update today text
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/layout.tsx
Labels: C-feature
