Repository AtB-AS/planner-web, pull requests merged in 2025-03, with the labels that each got.

#493 feat: add location search history
  src/components/search/__tests__/search.test.tsx
  src/components/search/index.ts
  src/components/search/search.module.css
  src/components/search/search.tsx
  src/components/search/use-geolocation.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/layout.tsx
  src/translations/components/search.ts
Labels: C-feature

#494 feat: update location search dropdown styling
  src/components/search/search.module.css
  src/components/search/search.tsx
Labels: C-feature

#498 feat: add border around search dropdown
  src/components/search/search.module.css
Labels: C-feature

#500 test: k6 improvements for core web vitals
  e2e-tests/k6/.gitignore
  e2e-tests/k6/conf/options.ts
  e2e-tests/k6/pages/assistant.ts
  e2e-tests/k6/pages/departures.ts
  e2e-tests/k6/scenario/assistant.ts
  e2e-tests/k6/scenario/departures.ts
  src/components/search/swap-button/index.tsx
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/departures/details/estimated-call-rows.tsx
  src/page-modules/departures/layout.tsx
Labels: test

#504 chore(deps): bump next.js to 14.2.25
  package.json
  yarn.lock
Labels: C-chore

#505 chore: Add to estimated calls for trip search
  src/page-modules/assistant/server/journey-planner/validators.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/utils.ts
Labels: C-chore

#508 Revert "chore: Upgrade tpw to new colors and buttons (#499)"
  package.json
  public/fb.svg
  public/ig.svg
  public/twitter.svg
  public/widget/IYFwRkA/2.36.0/planner-web.css
  public/widget/IYFwRkA/2.36.1/planner-web.css
  src/components/button/button.module.css
  src/components/button/utils.tsx
  src/components/map/map-header.tsx
  src/components/search/search.module.css
  src/components/tab-link/tab-link.module.css
  src/layouts/shared/footer.module.css
  src/layouts/shared/footer.tsx
  src/layouts/shared/page-header.module.css
  src/layouts/shared/page-header.tsx
  src/modules/search-time/selector/selector.module.css
  src/modules/transport-mode/filter/filter.module.css
  src/page-modules/assistant/assistant.module.css
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/line-filter/line-filter.module.css
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/departures.module.css
  src/page-modules/departures/layout.tsx
  src/page-modules/departures/stop-place/stop-place.module.css
  src/page-modules/widget/available-widgets/IYFwRkA/manifest.json
  src/widget/vite.config.js
  src/widget/widget.module.css
  yarn.lock
Labels: C-chore

#506 feat: use autocomplete data instead of reverse geocoder for trip search and departure
  src/components/map/map-header.tsx
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/trip-query-fetcher.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/page-modules/assistant/types.ts
  src/page-modules/assistant/utils.ts
  src/page-modules/departures/fetch-departure-query.ts
  src/page-modules/departures/utils.ts
Labels: C-feature

#509 fix: Update URL to privacy policy
  orgs/atb.json
Labels: C-bug
