Repository AtB-AS/planner-web, pull requests merged in 2025-04, with the labels that each got.

#516 fix: Notices to estimated call
  src/page-modules/assistant/journey-gql/trip-with-details.gql
  src/page-modules/assistant/journey-gql/via-trip-with-details.gql
  src/page-modules/assistant/journey-gql/via-trip.gql
  src/page-modules/assistant/server/journey-planner/index.ts
Labels: C-bug

#517 feat: add trip search accordion
  src/components/map/types.ts
  src/components/map/utils.ts
  src/modules/flexible/utils.ts
  src/modules/situations/__tests__/stop-place.test.tsx
  src/modules/transport-mode/types.ts
  src/page-modules/assistant/__tests__/assistant-data.fixture.ts
  src/page-modules/assistant/details-body/details-body.module.css
  src/page-modules/assistant/details-body/index.tsx
  src/page-modules/assistant/details/details-header/index.tsx
  src/page-modules/assistant/details/details.module.css
  src/page-modules/assistant/details/index.tsx
  src/page-modules/assistant/journey-gql/trip-with-details.gql
  src/page-modules/assistant/journey-gql/trip.gql
  src/page-modules/assistant/journey-gql/via-trip.gql
  src/page-modules/assistant/server/journey-planner/index.ts
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/assistant/trip/trip-pattern/__tests__/trip-pattern.test.tsx
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern-header.test.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/__tests__/trip-pattern.fixture.ts
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern-header/rail-replacement-bus.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css
  src/page-modules/assistant/trip/trip-pattern/utils.ts
  src/page-modules/assistant/types.ts
  src/page-modules/assistant/utils.ts
  src/page-modules/departures/__tests__/departure-data.fixture.ts
  src/page-modules/departures/__tests__/departure-details.test.tsx
  src/page-modules/departures/__tests__/departure.test.tsx
  src/page-modules/departures/details/estimated-call-rows.tsx
  src/page-modules/departures/server/journey-planner/index.ts
  src/page-modules/departures/stop-place/index.tsx
  src/page-modules/departures/types.ts
  src/translations/pages/assistant.ts
  src/widget/widget.ts
Labels: C-feature

#518 Revert "feat: use autocomplete data instead of reverse geocoder for trip search and departure (#506)"
  src/components/map/map-header.tsx
  src/page-modules/assistant/__tests__/assistant.test.tsx
  src/page-modules/assistant/details/utils.ts
  src/page-modules/assistant/trip-query-fetcher.ts
  src/page-modules/assistant/types.ts
  src/page-modules/assistant/utils.ts
  src/page-modules/departures/fetch-departure-query.ts
  src/page-modules/departures/utils.ts
Labels: C-feature

#521 feat(assistant): update VKT ticketBooking global message
  src/translations/pages/assistant.ts
Labels: C-feature

#520 feat: extend contact form with selector to specify which platform the ticket was purchases through
  src/page-modules/contact/refund/events.ts
  src/page-modules/contact/refund/forms/refund-ticket/appTicketRefund.tsx
  src/page-modules/contact/refund/refundFormMachine.ts
  src/page-modules/contact/types.ts
  src/page-modules/contact/validation/commonInputValidator.ts
  src/translations/pages/contact.ts
Labels: C-feature

#524 feat: Improved usability for accordion
  src/page-modules/assistant/details-body/index.tsx
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css
  src/translations/pages/assistant.ts
Labels: C-feature

#523 chore: remove bullet point about rule that no longer applies
  src/translations/pages/contact.ts
Labels: C-chore

#513 feat: add checkbox for showing only stop places on trip search
  src/components/checkbox/checkbox.module.css
  src/components/checkbox/checkbox.tsx
  src/components/checkbox/index.ts
  src/components/error-message/error-message.module.css
  src/components/error-message/error-message.tsx
  src/components/error-message/index.ts
  src/components/search/__tests__/search.test.tsx
  src/components/search/search.module.css
  src/components/search/search.tsx
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/components/form/file-input.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/index.ts
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/components/form/searchable-select/searchable-select.tsx
  src/page-modules/contact/components/form/select.tsx
  src/page-modules/contact/components/form/textarea.tsx
  src/page-modules/contact/components/form/time-selector.tsx
  src/page-modules/contact/components/index.tsx
  src/page-modules/contact/means-of-transport/forms/transportationForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/index.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/index.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/departures/client/geocoder/index.ts
  src/page-modules/departures/server/geocoder/index.ts
  src/pages/api/departures/autocomplete.ts
  src/translations/pages/assistant.ts
Labels: C-feature, TPW, :people_holding_hands: Team initiative

#527 feat: add message to inform users to not include personal information
  src/page-modules/contact/layouts/contact-page-layout.tsx
  src/page-modules/contact/layouts/layout.module.css
  src/translations/pages/contact.ts
Labels: C-feature

#530 fix: Fixed missing button-border in dark mode
  src/components/map/map.module.css
  src/page-modules/assistant/trip/trip-pattern/trip-pattern.module.css
Labels: C-bug

#514 fix: Oms colors and theme fixes
  package.json
  public/fb_dark.svg
  public/ig_dark.svg
  public/twitter_dark.svg
  src/components/button/button.tsx
  src/components/button/link.tsx
  src/components/button/utils.tsx
  src/components/icon/mono-icon.tsx
  src/layouts/shared/footer.module.css
  src/layouts/shared/footer.tsx
  src/layouts/shared/page-header.module.css
  src/layouts/shared/page-header.tsx
  src/page-modules/assistant/layout.tsx
  src/page-modules/assistant/trip/index.tsx
  src/page-modules/departures/layout.tsx
  src/utils/org-theme-definitions.ts
  yarn.lock
Labels: C-bug

#529 feat: extend validation bank account number in contact form
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/input.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundCarForm.tsx
  src/page-modules/contact/refund/forms/refund-and-travel-guarantee/refundTaxiForm.tsx
  src/page-modules/contact/refund/forms/refund-ticket/otherTicketRefund.tsx
  src/page-modules/contact/ticket-control/forms/feeComplaintForm.tsx
  src/page-modules/contact/validation/validationRules.ts
  src/translations/pages/contact.ts
Labels: C-feature

#534 feat: reduce maxSlack in viaTripQuery
  src/page-modules/assistant/server/journey-planner/index.ts
Labels: C-feature

#533 fix(accessibility): move label inside date/time fields to fix aria label issues in date/time components
  src/page-modules/contact/components/form/date-selector.tsx
  src/page-modules/contact/components/form/form.module.css
  src/page-modules/contact/components/form/time-selector.tsx
Labels: C-bug

#536 fix: crash in form validation due to unexpected input type
  src/page-modules/contact/validation/validationRules.ts
Labels: C-bug
