Repository AtB-AS/planner-web, pull requests merged in 2025-07, with the labels that each got.

#592 chore: deny missing consents in analytics.ts
  src/modules/firebase/analytics.ts
Labels: C-chore

#593 feat: update transportation icons
  package.json
  src/components/venue-icon/index.tsx
  src/modules/transport-mode/icon/index.tsx
  src/page-modules/assistant/details-body/index.tsx
  src/page-modules/assistant/trip/trip-pattern/index.tsx
  src/page-modules/contact/layouts/contact-page-layout.tsx
  yarn.lock
Labels: C-feature, TPW

#598 feat: feedback ticket control - remove ferry from transportation options
  src/page-modules/contact/ticket-control/forms/feedbackForm.tsx
Labels: C-feature

#599 fix: remove unexpected input property
  src/page-modules/contact/means-of-transport/means-of-transport-form-machine.ts
Labels: C-bug

#595 feat: Added withAccessLogging to all page accesses
  src/layouts/default.tsx
  src/modules/api-server/requesters/graphql-requester.ts
  src/modules/api-server/requesters/http-requester.ts
  src/modules/api-server/requesters/utils.ts
  src/modules/global-data/index.ts
  src/modules/global-data/types.ts
  src/modules/global-data/with-global-data.ts
  src/modules/logging/index.ts
  src/modules/logging/log-api-response.ts
  src/modules/logging/log-page-access.ts
  src/modules/logging/logger.ts
  src/modules/logging/timer.ts
  src/modules/logging/with-access-logging.ts
  src/modules/theme/index.ts
  src/pages/_error.tsx
  src/pages/assistant/[id].tsx
  src/pages/assistant/index.tsx
  src/pages/contact/error.tsx
  src/pages/contact/group-travel.tsx
  src/pages/contact/index.tsx
  src/pages/contact/lost-property.tsx
  src/pages/contact/means-of-transport/index.tsx
  src/pages/contact/refund.tsx
  src/pages/contact/success.tsx
  src/pages/contact/ticket-control/index.tsx
  src/pages/contact/ticketing/index.tsx
  src/pages/departures/[[...id]].tsx
  src/pages/departures/details/[id].tsx
  src/pages/widget/fullscreen/[[...version]].tsx
  src/pages/widget/index.tsx
Labels: C-feature

#601 chore: minor translation update
  src/translations/pages/contact.ts
Labels: C-chore
